import { Button, VerticalBox, GridBox, Spinner } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 480px;
    height: 110px;
    title: "power-menu-rs";

    callback request-shutdown();
    callback request-reboot();
    callback request-suspend();
    callback request-cancel();
    GridBox {
        Button {
            text: "Shutdown";
            clicked => {
                root.request-shutdown();
            }
        }

        Button {
            text: "Reboot";
            clicked => {
                root.request-reboot();
            }
        }

        Button {
            text: "Suspend";
            clicked => {
                root.request-suspend();
            }
        }

        Button {
            text: "Cancel";
            clicked => {
                root.request-cancel();
            }
        }
    }
}
